compile: controller/GameMaster.c controller/mapper.c controller/Player.c controller/Pokemon.c view/interfaz.c
	gcc `pkg-config --cflags gtk+-3.0` controller/GameMaster.c controller/mapper.c controller/Player.c controller/Pokemon.c view/interfaz.c -lm -pthread -o pthreadmon `pkg-config --libs gtk+-3.0`
